/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScorecardRouteImport } from './routes/scorecard'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TeamsRegisterRouteImport } from './routes/teams/register'
import { Route as AdminTeamsRouteImport } from './routes/admin/teams'
import { Route as AdminRequestsRouteImport } from './routes/admin/requests'
import { Route as AdminHealthRouteImport } from './routes/admin/health'
import { Route as TeamsTeamIdTurnoverRouteImport } from './routes/teams/$teamId/turnover'
import { Route as TeamsTeamIdSettingsRouteImport } from './routes/teams/$teamId/settings'
import { Route as TeamsTeamIdScorecardRouteImport } from './routes/teams/$teamId/scorecard'
import { Route as TeamsTeamIdLinkManagerRouteImport } from './routes/teams/$teamId/link-manager'
import { Route as TeamsTeamIdLinkManagerIndexRouteImport } from './routes/teams/$teamId/link-manager/index'
import { Route as TeamsTeamIdTurnoverTurnoverMetricsRouteImport } from './routes/teams/$teamId/turnover/turnover-metrics'
import { Route as TeamsTeamIdTurnoverTransitionHistoryRouteImport } from './routes/teams/$teamId/turnover/transition-history'
import { Route as TeamsTeamIdTurnoverPassTheBatonRouteImport } from './routes/teams/$teamId/turnover/pass-the-baton'
import { Route as TeamsTeamIdTurnoverDispatchTurnoverRouteImport } from './routes/teams/$teamId/turnover/dispatch-turnover'
import { Route as TeamsTeamIdLinkManagerStatsRouteImport } from './routes/teams/$teamId/link-manager/stats'
import { Route as TeamsTeamIdLinkManagerImportRouteImport } from './routes/teams/$teamId/link-manager/import'
import { Route as TeamsTeamIdLinkManagerCategoriesRouteImport } from './routes/teams/$teamId/link-manager/categories'

const ScorecardRoute = ScorecardRouteImport.update({
  id: '/scorecard',
  path: '/scorecard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TeamsRegisterRoute = TeamsRegisterRouteImport.update({
  id: '/teams/register',
  path: '/teams/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminRoute,
} as any)
const TeamsTeamIdTurnoverRoute = TeamsTeamIdTurnoverRouteImport.update({
  id: '/teams/$teamId/turnover',
  path: '/teams/$teamId/turnover',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdSettingsRoute = TeamsTeamIdSettingsRouteImport.update({
  id: '/teams/$teamId/settings',
  path: '/teams/$teamId/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdScorecardRoute = TeamsTeamIdScorecardRouteImport.update({
  id: '/teams/$teamId/scorecard',
  path: '/teams/$teamId/scorecard',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdLinkManagerRoute = TeamsTeamIdLinkManagerRouteImport.update({
  id: '/teams/$teamId/link-manager',
  path: '/teams/$teamId/link-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdLinkManagerIndexRoute =
  TeamsTeamIdLinkManagerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TeamsTeamIdLinkManagerRoute,
  } as any)
const TeamsTeamIdTurnoverTurnoverMetricsRoute =
  TeamsTeamIdTurnoverTurnoverMetricsRouteImport.update({
    id: '/turnover-metrics',
    path: '/turnover-metrics',
    getParentRoute: () => TeamsTeamIdTurnoverRoute,
  } as any)
const TeamsTeamIdTurnoverTransitionHistoryRoute =
  TeamsTeamIdTurnoverTransitionHistoryRouteImport.update({
    id: '/transition-history',
    path: '/transition-history',
    getParentRoute: () => TeamsTeamIdTurnoverRoute,
  } as any)
const TeamsTeamIdTurnoverPassTheBatonRoute =
  TeamsTeamIdTurnoverPassTheBatonRouteImport.update({
    id: '/pass-the-baton',
    path: '/pass-the-baton',
    getParentRoute: () => TeamsTeamIdTurnoverRoute,
  } as any)
const TeamsTeamIdTurnoverDispatchTurnoverRoute =
  TeamsTeamIdTurnoverDispatchTurnoverRouteImport.update({
    id: '/dispatch-turnover',
    path: '/dispatch-turnover',
    getParentRoute: () => TeamsTeamIdTurnoverRoute,
  } as any)
const TeamsTeamIdLinkManagerStatsRoute =
  TeamsTeamIdLinkManagerStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => TeamsTeamIdLinkManagerRoute,
  } as any)
const TeamsTeamIdLinkManagerImportRoute =
  TeamsTeamIdLinkManagerImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => TeamsTeamIdLinkManagerRoute,
  } as any)
const TeamsTeamIdLinkManagerCategoriesRoute =
  TeamsTeamIdLinkManagerCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => TeamsTeamIdLinkManagerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/profile': typeof ProfileRoute
  '/scorecard': typeof ScorecardRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/teams/register': typeof TeamsRegisterRoute
  '/admin/': typeof AdminIndexRoute
  '/teams/$teamId/link-manager': typeof TeamsTeamIdLinkManagerRouteWithChildren
  '/teams/$teamId/scorecard': typeof TeamsTeamIdScorecardRoute
  '/teams/$teamId/settings': typeof TeamsTeamIdSettingsRoute
  '/teams/$teamId/turnover': typeof TeamsTeamIdTurnoverRouteWithChildren
  '/teams/$teamId/link-manager/categories': typeof TeamsTeamIdLinkManagerCategoriesRoute
  '/teams/$teamId/link-manager/import': typeof TeamsTeamIdLinkManagerImportRoute
  '/teams/$teamId/link-manager/stats': typeof TeamsTeamIdLinkManagerStatsRoute
  '/teams/$teamId/turnover/dispatch-turnover': typeof TeamsTeamIdTurnoverDispatchTurnoverRoute
  '/teams/$teamId/turnover/pass-the-baton': typeof TeamsTeamIdTurnoverPassTheBatonRoute
  '/teams/$teamId/turnover/transition-history': typeof TeamsTeamIdTurnoverTransitionHistoryRoute
  '/teams/$teamId/turnover/turnover-metrics': typeof TeamsTeamIdTurnoverTurnoverMetricsRoute
  '/teams/$teamId/link-manager/': typeof TeamsTeamIdLinkManagerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/scorecard': typeof ScorecardRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/teams/register': typeof TeamsRegisterRoute
  '/admin': typeof AdminIndexRoute
  '/teams/$teamId/scorecard': typeof TeamsTeamIdScorecardRoute
  '/teams/$teamId/settings': typeof TeamsTeamIdSettingsRoute
  '/teams/$teamId/turnover': typeof TeamsTeamIdTurnoverRouteWithChildren
  '/teams/$teamId/link-manager/categories': typeof TeamsTeamIdLinkManagerCategoriesRoute
  '/teams/$teamId/link-manager/import': typeof TeamsTeamIdLinkManagerImportRoute
  '/teams/$teamId/link-manager/stats': typeof TeamsTeamIdLinkManagerStatsRoute
  '/teams/$teamId/turnover/dispatch-turnover': typeof TeamsTeamIdTurnoverDispatchTurnoverRoute
  '/teams/$teamId/turnover/pass-the-baton': typeof TeamsTeamIdTurnoverPassTheBatonRoute
  '/teams/$teamId/turnover/transition-history': typeof TeamsTeamIdTurnoverTransitionHistoryRoute
  '/teams/$teamId/turnover/turnover-metrics': typeof TeamsTeamIdTurnoverTurnoverMetricsRoute
  '/teams/$teamId/link-manager': typeof TeamsTeamIdLinkManagerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/profile': typeof ProfileRoute
  '/scorecard': typeof ScorecardRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/teams/register': typeof TeamsRegisterRoute
  '/admin/': typeof AdminIndexRoute
  '/teams/$teamId/link-manager': typeof TeamsTeamIdLinkManagerRouteWithChildren
  '/teams/$teamId/scorecard': typeof TeamsTeamIdScorecardRoute
  '/teams/$teamId/settings': typeof TeamsTeamIdSettingsRoute
  '/teams/$teamId/turnover': typeof TeamsTeamIdTurnoverRouteWithChildren
  '/teams/$teamId/link-manager/categories': typeof TeamsTeamIdLinkManagerCategoriesRoute
  '/teams/$teamId/link-manager/import': typeof TeamsTeamIdLinkManagerImportRoute
  '/teams/$teamId/link-manager/stats': typeof TeamsTeamIdLinkManagerStatsRoute
  '/teams/$teamId/turnover/dispatch-turnover': typeof TeamsTeamIdTurnoverDispatchTurnoverRoute
  '/teams/$teamId/turnover/pass-the-baton': typeof TeamsTeamIdTurnoverPassTheBatonRoute
  '/teams/$teamId/turnover/transition-history': typeof TeamsTeamIdTurnoverTransitionHistoryRoute
  '/teams/$teamId/turnover/turnover-metrics': typeof TeamsTeamIdTurnoverTurnoverMetricsRoute
  '/teams/$teamId/link-manager/': typeof TeamsTeamIdLinkManagerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/profile'
    | '/scorecard'
    | '/admin/health'
    | '/admin/requests'
    | '/admin/teams'
    | '/teams/register'
    | '/admin/'
    | '/teams/$teamId/link-manager'
    | '/teams/$teamId/scorecard'
    | '/teams/$teamId/settings'
    | '/teams/$teamId/turnover'
    | '/teams/$teamId/link-manager/categories'
    | '/teams/$teamId/link-manager/import'
    | '/teams/$teamId/link-manager/stats'
    | '/teams/$teamId/turnover/dispatch-turnover'
    | '/teams/$teamId/turnover/pass-the-baton'
    | '/teams/$teamId/turnover/transition-history'
    | '/teams/$teamId/turnover/turnover-metrics'
    | '/teams/$teamId/link-manager/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/scorecard'
    | '/admin/health'
    | '/admin/requests'
    | '/admin/teams'
    | '/teams/register'
    | '/admin'
    | '/teams/$teamId/scorecard'
    | '/teams/$teamId/settings'
    | '/teams/$teamId/turnover'
    | '/teams/$teamId/link-manager/categories'
    | '/teams/$teamId/link-manager/import'
    | '/teams/$teamId/link-manager/stats'
    | '/teams/$teamId/turnover/dispatch-turnover'
    | '/teams/$teamId/turnover/pass-the-baton'
    | '/teams/$teamId/turnover/transition-history'
    | '/teams/$teamId/turnover/turnover-metrics'
    | '/teams/$teamId/link-manager'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/profile'
    | '/scorecard'
    | '/admin/health'
    | '/admin/requests'
    | '/admin/teams'
    | '/teams/register'
    | '/admin/'
    | '/teams/$teamId/link-manager'
    | '/teams/$teamId/scorecard'
    | '/teams/$teamId/settings'
    | '/teams/$teamId/turnover'
    | '/teams/$teamId/link-manager/categories'
    | '/teams/$teamId/link-manager/import'
    | '/teams/$teamId/link-manager/stats'
    | '/teams/$teamId/turnover/dispatch-turnover'
    | '/teams/$teamId/turnover/pass-the-baton'
    | '/teams/$teamId/turnover/transition-history'
    | '/teams/$teamId/turnover/turnover-metrics'
    | '/teams/$teamId/link-manager/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ScorecardRoute: typeof ScorecardRoute
  TeamsRegisterRoute: typeof TeamsRegisterRoute
  TeamsTeamIdLinkManagerRoute: typeof TeamsTeamIdLinkManagerRouteWithChildren
  TeamsTeamIdScorecardRoute: typeof TeamsTeamIdScorecardRoute
  TeamsTeamIdSettingsRoute: typeof TeamsTeamIdSettingsRoute
  TeamsTeamIdTurnoverRoute: typeof TeamsTeamIdTurnoverRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scorecard': {
      id: '/scorecard'
      path: '/scorecard'
      fullPath: '/scorecard'
      preLoaderRoute: typeof ScorecardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teams/register': {
      id: '/teams/register'
      path: '/teams/register'
      fullPath: '/teams/register'
      preLoaderRoute: typeof TeamsRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teams/$teamId/turnover': {
      id: '/teams/$teamId/turnover'
      path: '/teams/$teamId/turnover'
      fullPath: '/teams/$teamId/turnover'
      preLoaderRoute: typeof TeamsTeamIdTurnoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/settings': {
      id: '/teams/$teamId/settings'
      path: '/teams/$teamId/settings'
      fullPath: '/teams/$teamId/settings'
      preLoaderRoute: typeof TeamsTeamIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/scorecard': {
      id: '/teams/$teamId/scorecard'
      path: '/teams/$teamId/scorecard'
      fullPath: '/teams/$teamId/scorecard'
      preLoaderRoute: typeof TeamsTeamIdScorecardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/link-manager': {
      id: '/teams/$teamId/link-manager'
      path: '/teams/$teamId/link-manager'
      fullPath: '/teams/$teamId/link-manager'
      preLoaderRoute: typeof TeamsTeamIdLinkManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/link-manager/': {
      id: '/teams/$teamId/link-manager/'
      path: '/'
      fullPath: '/teams/$teamId/link-manager/'
      preLoaderRoute: typeof TeamsTeamIdLinkManagerIndexRouteImport
      parentRoute: typeof TeamsTeamIdLinkManagerRoute
    }
    '/teams/$teamId/turnover/turnover-metrics': {
      id: '/teams/$teamId/turnover/turnover-metrics'
      path: '/turnover-metrics'
      fullPath: '/teams/$teamId/turnover/turnover-metrics'
      preLoaderRoute: typeof TeamsTeamIdTurnoverTurnoverMetricsRouteImport
      parentRoute: typeof TeamsTeamIdTurnoverRoute
    }
    '/teams/$teamId/turnover/transition-history': {
      id: '/teams/$teamId/turnover/transition-history'
      path: '/transition-history'
      fullPath: '/teams/$teamId/turnover/transition-history'
      preLoaderRoute: typeof TeamsTeamIdTurnoverTransitionHistoryRouteImport
      parentRoute: typeof TeamsTeamIdTurnoverRoute
    }
    '/teams/$teamId/turnover/pass-the-baton': {
      id: '/teams/$teamId/turnover/pass-the-baton'
      path: '/pass-the-baton'
      fullPath: '/teams/$teamId/turnover/pass-the-baton'
      preLoaderRoute: typeof TeamsTeamIdTurnoverPassTheBatonRouteImport
      parentRoute: typeof TeamsTeamIdTurnoverRoute
    }
    '/teams/$teamId/turnover/dispatch-turnover': {
      id: '/teams/$teamId/turnover/dispatch-turnover'
      path: '/dispatch-turnover'
      fullPath: '/teams/$teamId/turnover/dispatch-turnover'
      preLoaderRoute: typeof TeamsTeamIdTurnoverDispatchTurnoverRouteImport
      parentRoute: typeof TeamsTeamIdTurnoverRoute
    }
    '/teams/$teamId/link-manager/stats': {
      id: '/teams/$teamId/link-manager/stats'
      path: '/stats'
      fullPath: '/teams/$teamId/link-manager/stats'
      preLoaderRoute: typeof TeamsTeamIdLinkManagerStatsRouteImport
      parentRoute: typeof TeamsTeamIdLinkManagerRoute
    }
    '/teams/$teamId/link-manager/import': {
      id: '/teams/$teamId/link-manager/import'
      path: '/import'
      fullPath: '/teams/$teamId/link-manager/import'
      preLoaderRoute: typeof TeamsTeamIdLinkManagerImportRouteImport
      parentRoute: typeof TeamsTeamIdLinkManagerRoute
    }
    '/teams/$teamId/link-manager/categories': {
      id: '/teams/$teamId/link-manager/categories'
      path: '/categories'
      fullPath: '/teams/$teamId/link-manager/categories'
      preLoaderRoute: typeof TeamsTeamIdLinkManagerCategoriesRouteImport
      parentRoute: typeof TeamsTeamIdLinkManagerRoute
    }
  }
}

interface AdminRouteChildren {
  AdminHealthRoute: typeof AdminHealthRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminHealthRoute: AdminHealthRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminTeamsRoute: AdminTeamsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TeamsTeamIdLinkManagerRouteChildren {
  TeamsTeamIdLinkManagerCategoriesRoute: typeof TeamsTeamIdLinkManagerCategoriesRoute
  TeamsTeamIdLinkManagerImportRoute: typeof TeamsTeamIdLinkManagerImportRoute
  TeamsTeamIdLinkManagerStatsRoute: typeof TeamsTeamIdLinkManagerStatsRoute
  TeamsTeamIdLinkManagerIndexRoute: typeof TeamsTeamIdLinkManagerIndexRoute
}

const TeamsTeamIdLinkManagerRouteChildren: TeamsTeamIdLinkManagerRouteChildren =
  {
    TeamsTeamIdLinkManagerCategoriesRoute:
      TeamsTeamIdLinkManagerCategoriesRoute,
    TeamsTeamIdLinkManagerImportRoute: TeamsTeamIdLinkManagerImportRoute,
    TeamsTeamIdLinkManagerStatsRoute: TeamsTeamIdLinkManagerStatsRoute,
    TeamsTeamIdLinkManagerIndexRoute: TeamsTeamIdLinkManagerIndexRoute,
  }

const TeamsTeamIdLinkManagerRouteWithChildren =
  TeamsTeamIdLinkManagerRoute._addFileChildren(
    TeamsTeamIdLinkManagerRouteChildren,
  )

interface TeamsTeamIdTurnoverRouteChildren {
  TeamsTeamIdTurnoverDispatchTurnoverRoute: typeof TeamsTeamIdTurnoverDispatchTurnoverRoute
  TeamsTeamIdTurnoverPassTheBatonRoute: typeof TeamsTeamIdTurnoverPassTheBatonRoute
  TeamsTeamIdTurnoverTransitionHistoryRoute: typeof TeamsTeamIdTurnoverTransitionHistoryRoute
  TeamsTeamIdTurnoverTurnoverMetricsRoute: typeof TeamsTeamIdTurnoverTurnoverMetricsRoute
}

const TeamsTeamIdTurnoverRouteChildren: TeamsTeamIdTurnoverRouteChildren = {
  TeamsTeamIdTurnoverDispatchTurnoverRoute:
    TeamsTeamIdTurnoverDispatchTurnoverRoute,
  TeamsTeamIdTurnoverPassTheBatonRoute: TeamsTeamIdTurnoverPassTheBatonRoute,
  TeamsTeamIdTurnoverTransitionHistoryRoute:
    TeamsTeamIdTurnoverTransitionHistoryRoute,
  TeamsTeamIdTurnoverTurnoverMetricsRoute:
    TeamsTeamIdTurnoverTurnoverMetricsRoute,
}

const TeamsTeamIdTurnoverRouteWithChildren =
  TeamsTeamIdTurnoverRoute._addFileChildren(TeamsTeamIdTurnoverRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ScorecardRoute: ScorecardRoute,
  TeamsRegisterRoute: TeamsRegisterRoute,
  TeamsTeamIdLinkManagerRoute: TeamsTeamIdLinkManagerRouteWithChildren,
  TeamsTeamIdScorecardRoute: TeamsTeamIdScorecardRoute,
  TeamsTeamIdSettingsRoute: TeamsTeamIdSettingsRoute,
  TeamsTeamIdTurnoverRoute: TeamsTeamIdTurnoverRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
